In [9]:
#With Python
import csv

def calculate_rating_stats(data,industry=None):
    ratings=[]
    for row in data:
        if row[3]!='NULL' and (not industry or row[1]==industry):
            ratings.append(float(row[3]))
    max_rating=max(ratings)
    min_rating=min(ratings)
    avg_rating=sum(ratings)/len(ratings)
    return max_rating,min_rating,avg_rating

with open("D:\\Pandas\\chapter_3_assets\\1_intro\\movies.csv","r") as f:
    data=list(csv.reader(f))
    header =data[0]
    print("Header:",header)  #Header
    data=data[1:]

max_rating, min_rating,avg_rating = calculate_rating_stats(data)
print(f"All records: Min rating = {min_rating}, Max rating = {max_rating}, Avg rating = {avg_rating}")
    
max_rating, min_rating, avg_rating = calculate_rating_stats(data, industry="Bollywood")
print(f"Bollywood: Min rating = {min_rating}, Max rating = {max_rating}, Avg rating = {avg_rating}")
    
max_rating, min_rating, avg_rating = calculate_rating_stats(data, industry="Hollywood")
print(f"Hollywood: Min rating = {min_rating}, Max rating = {max_rating}, Avg rating = {avg_rating}")

Header: ['title', 'industry', 'release_year', 'imdb_rating', 'studio', 'budget', 'revenue', 'unit', 'currency', 'language']
All records: Min rating = 1.9, Max rating = 9.3, Avg rating = 7.919444444444445
Bollywood: Min rating = 1.9, Max rating = 8.4, Avg rating = 7.656250000000001
Hollywood: Min rating = 6.8, Max rating = 9.3, Avg rating = 8.130000000000003

In [11]:
import pandas as pd
df=pd.read_csv("D:\\Pandas\\chapter_3_assets\\1_intro\\movies.csv") #Dataframe is main object in Pandas library
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English

In [12]:
df.tail()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.0,950.0,Millions,INR,Hindi
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.0,12.5,Billions,INR,Kannada
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.0,3.6,Billions,INR,Telugu
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.5,12.0,Billions,INR,Telugu
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.8,6.5,Billions,INR,Telugu

In [13]:
df.sample(4)

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
21,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,400.0,2000.0,Millions,INR,Hindi
28,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.0,5.9,Billions,INR,Hindi

In [14]:
df[2:6]  #6 not included

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English

In [15]:
df.shape

(37, 10)

In [16]:
df["imdb_rating"]
df.imdb_rating

0     8.3
1     7.0
2     6.8
3     7.9
4     6.8
5     9.3
6     8.6
7     8.0
8     8.5
9     7.9
10    8.6
11    7.8
12    9.2
13    9.0
14    9.0
15    8.2
16    8.5
17    8.4
18    8.4
19    6.9
20    7.8
21    8.0
22    8.4
23    7.4
24    7.2
25    8.3
26    8.1
27    8.1
28    NaN
29    8.3
30    8.1
31    1.9
32    8.4
33    8.4
34    7.6
35    8.0
36    8.0
Name: imdb_rating, dtype: float64

In [17]:
type(df.imdb_rating)  #Column in df is series

pandas.core.series.Series

In [18]:
dir(df.imdb_rating)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__bool__',
 '__class__',
 '__column_consortium_standard__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_binop',
 '_cacher',
 '_can_hold_na',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_expanddim_from_mgr',
 '_constructor_from_mgr',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_duplicated',
 '_expanddim_from_mgr',
 '_find_valid_index',
 '_flags',
 '_flex_method',
 '_from_mgr',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_index_resolvers',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_rows_with_mask',
 '_get_value',
 '_get_values_tuple',
 '_get_with',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_cached',
 '_is_copy',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_item_cache',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_map_values',
 '_maybe_update_cacher',
 '_memory_usage',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_name',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_references',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_single',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_labels',
 '_set_name',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_shift_with_freq',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'backfill',
 'between',
 'between_time',
 'bfill',
 'bool',
 'case_when',
 'clip',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'interpolate',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'list',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'set_flags',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'struct',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs']

In [19]:
df.imdb_rating.min(),df.imdb_rating.max(),df.imdb_rating.mean()

(1.9, 9.3, 7.919444444444445)

In [26]:
b=df[df.industry=="Bollywood"]
b
b.imdb_rating.min(),b.imdb_rating.max(),b.imdb_rating.mean()

(1.9, 8.4, 7.656250000000001)

In [27]:
h=df[df.industry=="Hollywood"]
h
h.imdb_rating.min(),h.imdb_rating.max(),h.imdb_rating.mean()

(6.8, 9.3, 8.130000000000003)

In [29]:
#Final

df = pd.read_csv("D:\\Pandas\\chapter_3_assets\\1_intro\\movies.csv")
print("All movies: Min=", df.imdb_rating.min(), "Max=", df.imdb_rating.max(), "Avg=", df.imdb_rating.mean())

df_b = df[df.industry=="Bollywood"]
df_h = df[df.industry=="Hollywood"]

print("Bollywood: Min=", df_b.imdb_rating.min(), "Max=", df_b.imdb_rating.max(), "Avg=", df_b.imdb_rating.mean())
print("Hollywood: Min=", df_h.imdb_rating.min(), "Max=", df_h.imdb_rating.max(), "Avg=", df_h.imdb_rating.mean())

All movies: Min= 1.9 Max= 9.3 Avg= 7.919444444444445
Bollywood: Min= 1.9 Max= 8.4 Avg= 7.656250000000001
Hollywood: Min= 6.8 Max= 9.3 Avg= 8.130000000000003